### ISSUE TITLE
config not loading

### ISSUE THREAD

**Issue by largenton** [simply-kel/SimplyStatus-fabric#2]
Error from mod menu:

java.lang.NullPointerException: Cannot read field "logo" because "en.simplykel.simplystatus.Client.ASSETS" is null

Additional (I don't think it's important):
Os - windows 10
Minecraft - 1.19.4
java - Eclipse Adoptium JDK 17.0.1+12

**Comment by simply-kel** [comment]
Can you send me the full error log, because it's hard to understand what's going on here.

**Comment by largenton** [comment]
Here is the part with the error from the last logo:
 [Render thread/ERROR]: Error from mod 'simplystatus'
java.lang.NullPointerException: Cannot read field "logo" because "ru.simplykel.simplystatus.Client.ASSETS" is null
	at ru.simplykel.simplystatus.config.gui.category.AssetsConfigs.getCategory(AssetsConfigs.java:18) ~[simplystatus-1.7.0-b1.jar:?]
	at ru.simplykel.simplystatus.config.gui.ConfigScreen.buildScreen(ConfigScreen.java:35) ~[simplystatus-1.7.0-b1.jar:?]
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:57) ~[modmenu-6.1.0-rc.4.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:114) ~[modmenu-6.1.0-rc.4.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:427) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1079) ~[client-intermediary.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:14) ~[modmenu-6.1.0-rc.4.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:187) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_442.method_25402(class_442.java:308) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:540) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:234) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1241) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[fabric-loader-0.14.17-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.17.jar:?]

**Comment by simply-kel** [comment]
I don't know how it happened, but I don't get this error when I clear configurations and run them with new versions of the mods. I'll leave it for now, maybe someone else will have
